# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: doc/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - htmlzip

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.6
  install:
    - requirements: doc/requirements.txt
    - requirements: qchem/requirements.txt
    - method: pip
      path: .
    - method: pip
      path: qchem

build:
  image: latest
