fixes:
  - "pennylane_qchem/::qchem/pennylane_qchem/"
  - "/home/runner/work/pennylane/pennylane/pennylane/::pennylane/"

ignore:
  - "pennylane/devices/tests/*"

codecov:
    notify:
        after_n_builds: 6

comment:
    after_n_builds: 6
