ignore:
  - "pennylane/devices/tests/*"
  - "pennylane/data/base/_lazy_modules.py"
  - "pennylane/logging/*"
  - "pennylane/compiler/python_compiler/*"

codecov:
  notify:
    after_n_builds: 1

comment:
  after_n_builds: 1
coverage:

  status:
    project:
      default:
        threshold: 0.02%
