ignore:
  - "pennylane/devices/tests/*"

codecov:
  notify:
    after_n_builds: 1

comment:
  after_n_builds: 9
coverage:

  status:
    project:
      default:
        threshold: 0.02%
  after_n_builds: 1
