# Defines layered software architecture of PennyLane
layers = ["ui", "tertiary", "auxiliary", "core"]

exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]

source_roots = [
    ".",
]

# Forbids circular dependencies to be defined WITHIN this tach.toml file.
# NOTE: This does not check anything inside the source code for problems.
forbid_circular_dependencies = true

## UI module(s)
# Nothing in the source code should be able to import anything from top-level.
# This access point is restricted as it is here primarily for user convenience.

[[modules]]
path = "pennylane"
layer = "ui"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.transforms", "pennylane.decomposition", "pennylane.ops", "pennylane.resource", "pennylane.pauli", "pennylane.operation", "pennylane.core.operator", "pennylane.capture", "pennylane.qchem", "pennylane.devices", "pennylane.templates", "pennylane.workflow"]

## CLOSED module(s)
# No module can define dependencies to the following set of modules in this tach.toml file.

# NOTE: visibility = [] just means no module in this file can declare
# `depends_on = [<insert-closed-module>]` within this file.

[[modules]]
path = "pennylane.ftqc"
visibility = []
depends_on = ["pennylane.operation", "pennylane.tape", "pennylane.queuing", "pennylane.devices", "pennylane.transforms", "pennylane.decomposition", "pennylane.capture", "pennylane.ops", "pennylane.measurements", "pennylane", "pennylane.drawer", "pennylane.wires", "pennylane.math"]

[[modules]]
path = "pennylane.labs"
visibility = []
depends_on = ["pennylane.compiler", "pennylane.workflow", "pennylane", "pennylane.pauli", "pennylane.templates.subroutines", "pennylane.liealg", "pennylane.templates", "pennylane.queuing", "pennylane.decomposition", "pennylane.operation", "pennylane.measurements", "pennylane.typing", "pennylane.capture", "pennylane.tape", "pennylane.math", "pennylane.ops", "pennylane.wires", "pennylane.estimator", "pennylane.transforms", "pennylane.allocation"]

## UTILITY modules

[[modules]]
path = "pennylane.exceptions"
utility = true
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]


[[modules]]
path = "pennylane._class_property"
utility = true
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

[[modules]]
path = "pennylane.concurrency"
utility = true
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

[[modules]]
path = "pennylane._entry_points_utils"
utility = true
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.devices"]

## CORE module(s)
# These modules are fundamental to the PennyLane ecosystem and
# they cannot depend on any module "lower" than them.

[[modules]]
path = "pennylane.control_flow"
layer = "core"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.math", "pennylane.compiler", "pennylane.capture", "pennylane.typing"]

[[modules]]
path = "pennylane.math"
depends_on = ["pennylane._grad", "pennylane.numpy"]
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.pytrees"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.numpy"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.wires"
depends_on = ["pennylane.math", "pennylane.pytrees"]
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.logging"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.about"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane._version"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.queuing"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.configuration"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.compiler"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.boolean_fn"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane.typing"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "core"

[[modules]]
path = "pennylane._grad"
layer = "core"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.capture", "pennylane.compiler"]

[[modules]]
path = "pennylane.circuit_graph"
layer = "core"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.measurements", "pennylane.wires", "pennylane.operation", "pennylane.queuing", "pennylane.resource", "pennylane.ops"]

[[modules]]
path = "pennylane.allocation"
layer = "core"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.math", "pennylane.operation", "pennylane.capture", "pennylane.wires"]

[[modules]]
path = "pennylane.measurements"
layer = "core"
depends_on = ["pennylane.capture", "pennylane.math", "pennylane.wires", "pennylane.operation", "pennylane.core.operator", "pennylane.ops", "pennylane.queuing", "pennylane.typing", "pennylane.pytrees"]
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

## AUXILIARY module(s)
# These modules can only import from CORE modules and within their layer.

[[modules]]
path = "pennylane.shadows"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.tape", "pennylane.ops", "pennylane.transforms.core"]

[[modules]]
path = "pennylane.gradients"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.transforms.core", "pennylane.operation", "pennylane.transforms", "pennylane.devices", "pennylane.ops", "pennylane.decomposition", "pennylane.tape", "pennylane.workflow", "pennylane.pulse", "pennylane.pauli"]

[[modules]]
path = "pennylane.optimize"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.gradients", "pennylane.pauli", "pennylane.workflow", "pennylane.transforms.core", "pennylane.tape", "pennylane.templates", "pennylane.ops"]

[[modules]]
path = "pennylane.pulse"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.operation", "pennylane.ops"]

# TEMPLATES MODULE

[[modules]]
path = "pennylane.templates"
# Once all submodules are cleaned up, uncomment the following and delete the submodules
# layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.ops", "pennylane.templates.layer", "pennylane.capture", "pennylane.control_flow", "pennylane.pytrees", "pennylane.templates.layers", "pennylane.queuing", "pennylane.templates.swapnetworks", "pennylane.typing", "pennylane", "pennylane.templates.tensornetworks", "pennylane.operation", "pennylane.decomposition", "pennylane.math", "pennylane.templates.embeddings", "pennylane.wires", "pennylane.templates.subroutines"]

[[modules]]
path = "pennylane.templates.embeddings"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.decomposition", "pennylane.capture", "pennylane.ops", "pennylane.operation"]

[[modules]]
path = "pennylane.templates.layers"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.capture", "pennylane.decomposition", "pennylane.operation", "pennylane.templates.subroutines", "pennylane.ops", "pennylane.templates.embeddings"]

[[modules]]
path = "pennylane.templates.subroutines"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.ops", "pennylane.tape", "pennylane.resource", "pennylane.capture", "pennylane.decomposition", "pennylane.pauli", "pennylane.templates", "pennylane.gradients", "pennylane.operation", "pennylane.templates.embeddings"]

[[modules]]
path = "pennylane.templates.swapnetworks"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.ops", "pennylane.operation"]

[[modules]]
path = "pennylane.templates.tensornetworks"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.tape", "pennylane.operation"]

[[modules]]
path = "pennylane.templates.layer"
layer = "auxiliary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

# Bottom two must be addressed in another PR, too large of an effort

# [[modules]]
# path = "pennylane.templates.state_preparations"
# layer = "auxiliary"
# cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

## TERTIARY module(s)
# These modules can only import from CORE, AUXILIARY and modules within their layer.

[[modules]]
path = "pennylane.registers"
depends_on = []
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "tertiary"

[[modules]]
path = "pennylane.io"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.registers", "pennylane.operation", "pennylane.workflow", "pennylane.estimator", "pennylane.devices", "pennylane.tape", "pennylane.templates", "pennylane.ops", "pennylane.transforms"]

[[modules]]
path = "pennylane.qnn"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]

[[modules]]
path = "pennylane.qaoa"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.operation", "pennylane.templates", "pennylane.ops"]

[[modules]]
path = "pennylane.kernels"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "tertiary"

[[modules]]
path = "pennylane.data"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
layer = "tertiary"
depends_on = ["pennylane.operation", "pennylane.qchem", "pennylane.ops"]

[[modules]]
path = "pennylane.liealg"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.pauli", "pennylane.ops", "pennylane.operation"]

[[modules]]
path = "pennylane.fermi"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.pauli"]

[[modules]]
path = "pennylane.bose"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.pauli"]

[[modules]]
path = "pennylane.spin"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.ops", "pennylane.fermi", "pennylane.qchem"]

[[modules]]
path = "pennylane.drawer"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.workflow", "pennylane.operation", "pennylane.decomposition", "pennylane.templates", "pennylane.ops", "pennylane.tape"]

[[modules]]
path = "pennylane.fourier"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.tape", "pennylane.workflow", "pennylane.transforms", "pennylane.ops", "pennylane.operation", "pennylane.transforms.core", "pennylane.capture", "pennylane.decomposition"]

[[modules]]
path = "pennylane.noise"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.templates", "pennylane.tape", "pennylane.decomposition", "pennylane.transforms.core", "pennylane.ops", "pennylane.transforms", "pennylane.devices", "pennylane.workflow", "pennylane.operation"]

[[modules]]
path = "pennylane.debugging"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.ops", "pennylane.tape", "pennylane.transforms.core", "pennylane.devices"]

[[modules]]
path = "pennylane.qcut"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.transforms", "pennylane.workflow", "pennylane.pauli", "pennylane.operation", "pennylane.decomposition", "pennylane.transforms.core", "pennylane.ops", "pennylane.devices", "pennylane.tape"]

[[modules]]
path = "pennylane.estimator"
layer = "tertiary"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.qchem", "pennylane.templates", "pennylane.workflow", "pennylane.operation", "pennylane.ops"]

## UNSORTED module(s)
# Due to circular import problems, these modules below have incorrect dependencies
# and need to be parsed and fixed accordingly.

# These are left temporarily to depend on ANYTHING but the closed modules at the top of this file.

[[modules]]
path = "pennylane.transforms.core"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.capture", "pennylane.measurements", "pennylane.operation", "pennylane._grad", "pennylane", "pennylane.queuing", "pennylane.tape", "pennylane.pytrees", "pennylane.math", "pennylane.typing"]

[[modules]]
path = "pennylane.operation"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane", "pennylane.math", "pennylane.core.operator", "pennylane.typing"]

[[modules]]
path = "pennylane.core.operator"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.capture", "pennylane.typing", "pennylane", "pennylane.math", "pennylane.wires", "pennylane.pytrees", "pennylane.queuing"]

[[modules]]
path = "pennylane.ops"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.capture", "pennylane.measurements", "pennylane.templates.subroutines", "pennylane.templates.embeddings", "pennylane.decomposition", "pennylane.queuing", "pennylane.pytrees", "pennylane.typing", "pennylane.control_flow", "pennylane.pauli", "pennylane.numpy", "pennylane.pulse", "pennylane.tape", "pennylane.wires", "pennylane.operation", "pennylane.allocation", "pennylane.workflow", "pennylane", "pennylane.math", "pennylane.templates", "pennylane.compiler"]

[[modules]]
path = "pennylane.tape"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.measurements", "pennylane.typing", "pennylane.templates", "pennylane.wires", "pennylane.queuing", "pennylane", "pennylane.allocation", "pennylane.ops", "pennylane.pytrees", "pennylane.capture", "pennylane.operation"]

[[modules]]
path = "pennylane.qchem"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.pauli", "pennylane.wires", "pennylane.fermi", "pennylane.math", "pennylane.numpy", "pennylane", "pennylane.bose", "pennylane.ops"]

[[modules]]
path = "pennylane.transforms"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane", "pennylane.wires", "pennylane.measurements", "pennylane.capture", "pennylane.queuing", "pennylane.templates", "pennylane.operation", "pennylane.decomposition", "pennylane.typing", "pennylane.math", "pennylane.ops", "pennylane.transforms.core", "pennylane.allocation", "pennylane.tape", "pennylane.pauli"]

[[modules]]
path = "pennylane.capture"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane", "pennylane.ops", "pennylane.workflow", "pennylane.transforms.core", "pennylane.control_flow", "pennylane._grad", "pennylane.measurements", "pennylane.operation", "pennylane.math"]


[[modules]]
path = "pennylane.pauli"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.queuing", "pennylane.math", "pennylane.ops", "pennylane", "pennylane.typing", "pennylane.operation", "pennylane.wires"]

[[modules]]
path = "pennylane.resource"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.tape", "pennylane.devices", "pennylane.operation", "pennylane.ops", "pennylane.qnn", "pennylane.measurements", "pennylane"]

[[modules]]
path = "pennylane.decomposition"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.operation", "pennylane.math", "pennylane.ops", "pennylane.queuing", "pennylane.allocation", "pennylane.capture", "pennylane", "pennylane.wires"]

[[modules]]
path = "pennylane.devices"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.pulse", "pennylane.configuration", "pennylane.logging", "pennylane.decomposition", "pennylane.transforms", "pennylane.wires", "pennylane.queuing", "pennylane.typing", "pennylane._version", "pennylane.boolean_fn", "pennylane.operation", "pennylane.capture", "pennylane.templates.subroutines", "pennylane.math", "pennylane.numpy", "pennylane.ops", "pennylane", "pennylane.pauli", "pennylane.tape", "pennylane.measurements", "pennylane.transforms.core"]

[[modules]]
path = "pennylane.workflow"
cannot_depend_on = ["pennylane.ftqc", "pennylane.labs"]
depends_on = ["pennylane.transforms", "pennylane.tape", "pennylane.typing", "pennylane.queuing", "pennylane.debugging", "pennylane", "pennylane.pytrees", "pennylane.capture", "pennylane.transforms.core", "pennylane.logging", "pennylane.measurements", "pennylane.math"]

