# Copyright 2026 Xanadu Quantum Technologies Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Contains the ``TrotterCDF`` template for Compressed Double Factorization Hamiltonians."""

from collections import defaultdict

import numpy as np

from pennylane import math
from pennylane.control_flow import for_loop
from pennylane.core.operator import Operator2
from pennylane.decomposition import add_decomps, register_condition, register_resources
from pennylane.ops import CNOT, RZ, GlobalPhase, IsingZZ, PhaseShift
from pennylane.ops.op_math.controlled2 import flip_zero_control as flip_zero_control2
from pennylane.templates.subroutines.qchem.basis_rotation import BasisRotation
from pennylane.typing import Complex, Wire

from ._trotter_utils import _emit_one_body_rz, _emit_two_body_isingzz, _run_trotter_steps

# pylint: disable=too-many-arguments, no-value-for-parameter, unused-argument


class TrotterCDF(Operator2):
    r"""Second-order Trotter time evolution for a Compressed Double Factorization (CDF) Hamiltonian.

    This template realizes :math:`U \approx e^{-iHt}` for an electronic-structure Hamiltonian in
    the Compressed Double Factorization (CDF) form (see `arXiv:2506.15784, Sec. III A
    <https://arxiv.org/abs/2506.15784>`__). :math:`H` consists of a one-body fragment and
    :math:`L` two-body fragments, each diagonal in its own orbital basis:

    .. math::

        H = C + \sum_{p} \epsilon_{p}\, \tilde{n}^{(0)}_{p}
            + \sum_{l=1}^{L} \sum_{p,q} \lambda^{(l)}_{pq}\, \tilde{n}^{(l)}_{p} \tilde{n}^{(l)}_{q} ,

    where :math:`n_p` is the number operator of orbital :math:`p`,
    :math:`\tilde{n}^{(l)}_{p} = \mathcal{U}^{(l)} n_{p} \mathcal{U}^{(l)\dagger}` is its rotation
    into the basis of fragment :math:`l`, and :math:`C` is a scalar constant.

    The input encodes the *regrouped* single-boson form of this Hamiltonian: after substituting
    :math:`n_p = (I - Z_p)/2`, all single-site :math:`Z` terms (including those generated by
    expanding the two-body :math:`\tilde{n}_p \tilde{n}_q`) are collected into the one-body
    fragment and all constants into :math:`C`, so each two-body fragment retains only its two-site
    :math:`Z_p Z_q` couplings. The input tensors therefore map to this regrouped form as:

    * ``leaf_tensors[l]``: the :math:`N \times N` orbital rotation :math:`\mathcal{U}^{(l)} =`
      :class:`~.BasisRotation` ``(leaf_tensors[l])`` of fragment :math:`l` (applied to both spin
      sectors);
    * ``core_tensors[0]``: the (regrouped) one-body tensor, whose diagonal sets the *single-site*
      :class:`~.RZ` angles of the one-body layer;
    * ``core_tensors[l]`` (:math:`l \geq 1`): the symmetric two-body tensors, whose entries set
      the *two-site* :class:`~.IsingZZ` angles of the two-body layers;
    * ``nuc_constant``: the constant :math:`C`, applied together with the identity terms from the
      mapping as a single :class:`~.GlobalPhase`.

    Note that "one-body"/"two-body" count number operators (:math:`n_p`, :math:`n_p n_q`), not
    Pauli weight; the regrouping is what lets each two-body layer use only two-site
    :class:`~.IsingZZ` gates.

    Args:
        evolution_time (float): Total evolution time ``t``.
        num_trotter_steps (int): Number of second-order Trotter steps.
        hamiltonian (dict): A CDF Hamiltonian as a dictionary with keys ``nuc_constant``,
            ``core_tensors``, and ``leaf_tensors``. The expected shapes are
            ``core_tensors: (L+1, N, N)`` (diagonal per fragment) and
            ``leaf_tensors: (L+1, N, N)``, where ``N`` is the number of orbitals and
            ``L`` is the number of two-body fragments.
        wires (Wires): The system wires. CDF expects ``2N`` wires (alpha / beta interleaved).
        double_phase (bool): Only affects the controlled decomposition. If ``False`` (default),
            :func:`~pennylane.ctrl` produces a genuine controlled unitary
            :math:`\text{diag}(1, U)` where :math:`U = e^{-iHt}` is the Trotter evolution.
            If ``True``, it produces :math:`\text{diag}(U, U^\dagger)` instead, leading to the
            double phase trick for Hadamard test circuits (see `Fig. 6 <https://arxiv.org/abs/2506.15784>`__ and usage details below).

    **Example**

    Let us create mock CDF Hamiltonian data with the correct tensor shapes and evolve
    with a few Trotter steps.

    .. code-block:: python

        rng = np.random.default_rng(42)
        N = 2  # orbitals
        L = 1  # two-body fragments
        hamiltonian = {
            "core_tensors": rng.random((L + 1, N, N)),
            "leaf_tensors": rng.random((L + 1, N, N)),
            "nuc_constant": 0.5,
        }

        gate_set = {"BasisRotation", "RZ", "IsingZZ", "GlobalPhase", "ForLoop"}

        @qp.qjit
        @qp.transforms.decompose(gate_set=gate_set)
        @qp.qnode(qp.device("lightning.qubit", wires=2 * N))
        def trotter_circuit():
            qp.TrotterCDF(
                evolution_time=1.0, num_trotter_steps=10, hamiltonian=hamiltonian,
                wires=range(2 * N),
            )
            return qp.state()

    We can inspect the quantum resources required. Note that the order of the keys in
    the ``quantum_operations`` dictionary is not guaranteed, so we sort it before printing:

    >>> specs = qp.specs(trotter_circuit)()["resources"].quantum_operations
    >>> dict(sorted(specs.items()))
    {'GlobalPhase': 1, 'IsingZZ': 120, 'PhaseShift': 62, 'RZ': 40, 'SingleExcitation': 62}

    The :class:`~.PhaseShift` and :class:`~.SingleExcitation` gates are due to
    :class:`~.BasisRotation` decomposing further on ``lightning.qubit``.

    .. details ::
        :title: Usage Details

        Controlling this operator with :func:`~pennylane.ctrl` produces by default a genuine
        controlled evolution :math:`\text{diag}(1, U)` (assuming a single control wire),
        where :math:`U = e^{-iHt}` is the Trotter evolution.

        With ``double_phase=True``, :func:`~pennylane.ctrl` instead produces the double-phase Hadamard-test circuit
        of `Fig. 6 of arXiv:2506.15784 <https://arxiv.org/abs/2506.15784>`__, which realizes
        :math:`\text{diag}(U, U^\dagger)` (control-0 branch :math:`U = e^{-iHt}`, control-1 branch :math:`U^\dagger = e^{+iHt}`).

        In this decomposition, each diagonal rotation block is sandwiched by ``CNOT`` gates from the control wire (an
        ancilla-system ``ZZ`` coupling).

        .. code-block::

            double_phase=True:

                c: ─╭●──────┤ ->        c: ─╭●────────╭●─┤
            wires: ─╰RZ(2ϕ)─┤       wires: ─╰X──RZ(ϕ)─╰X─┤

        This is not a true controlled operation, but can be used to reduce the cost in Hadamard test circuits instead of the controlled evolution.

    .. details ::
        :title: Implementation Details

        This section shows how the CDF Hamiltonian is turned into the concrete gate angles, making
        every numerical prefactor explicit. Throughout we use :math:`n_p = (I - Z_p)/2`
        and the PennyLane conventions
        :math:`RZ(\theta) = e^{-i\theta Z/2}` and
        :math:`IsingZZ(\theta) = e^{-i\theta\, Z\otimes Z/2}`.

        **1. Fragment splitting and second-order Trotter**
        The Hamiltonian splits into :math:`L+1` fragments, :math:`H = C + \sum_{l=0}^{L} H_l`, the
        one-body fragment :math:`H_0` and :math:`L` two-body fragments :math:`H_l`,

        .. math::

            H_0 = \sum_{p} \epsilon_{p}\, \tilde{n}^{(0)}_{p} ,
            \qquad
            H_l = \sum_{p,q} \lambda^{(l)}_{pq}\, \tilde{n}^{(l)}_{p} \tilde{n}^{(l)}_{q}
            \quad (l \ge 1) ,

        with :math:`\tilde{n}^{(l)}_{p} = \mathcal{U}^{(l)} n_p \mathcal{U}^{(l)\dagger}` and the scalar
        :math:`C =` ``nuc_constant`` (handled in step 5). With :math:`n =` ``num_trotter_steps`` and
        step duration :math:`\Delta t = t/n`, :math:`e^{-iHt}` is approximated by :math:`n` repetitions
        of the second-order (Strang) step

        .. math::

            S_2(\Delta t) = \Big(\prod_{l=1}^{L} e^{-i H_l \Delta t/2}\Big)\,
                            e^{-i H_0 \Delta t}\,
                            \Big(\prod_{l=L}^{1} e^{-i H_l \Delta t/2}\Big) ,

        which visits each two-body fragment *twice* per step (at the half-step duration
        ``first_order_time_step`` :math:`= \Delta t/2`) and the central one-body fragment *once* (at the
        full :math:`\Delta t`). The next steps derive :math:`e^{-i H_l \tau}` for a single fragment and
        duration :math:`\tau`.

        **2. Evolving a fragment**
        The fragments are optimized and derived via :doc:`compressed double factorization <demos/tutorial_how_to_build_compressed_double_factorized_hamiltonians>`.
        Here, each fragment is diagonal in its own orbital basis,
        :math:`H_l = \mathcal{U}^{(l)} D_l\, \mathcal{U}^{(l)\dagger}`, where
        :math:`\mathcal{U}^{(l)} =` ``leaf_tensors[l]`` and :math:`D_l` is diagonal, so

        .. math::

            e^{-i H_l \tau} = \mathcal{U}^{(l)}\, e^{-i D_l \tau}\, \mathcal{U}^{(l)\dagger} .

        This is implemented as a :class:`~.BasisRotation` :math:`\mathcal{U}^{(l)}` (applied to the
        :math:`\alpha` and :math:`\beta` spin channels separately), the diagonal rotations for :math:`e^{-i D_l \tau}`
        (see steps 3-4 below), and the inverse rotation. Consecutive fragment rotations are merged as
        :math:`\mathcal{U}^{(l-1)\dagger}\mathcal{U}^{(l)}`, so only one basis rotation is emitted per
        fragment boundary.

        **3. One-body diagonal**
        The one-body generator is :math:`D_0 = \sum_p \epsilon_p\, n_p`, with
        :math:`\epsilon_p =` ``core_tensors[0][p, p]``. Using :math:`n_p=(I-Z_p)/2`,

        .. math::

            \epsilon_p\, n_p = \frac{\epsilon_p}{2}\, I - \frac{\epsilon_p}{2}\, Z_p ,

        so the :math:`Z_p` piece over duration :math:`\tau` is
        :math:`e^{+i(\epsilon_p/2) Z_p \tau} = RZ(-\epsilon_p \tau)`. The one-body fragment is the
        central full :math:`\Delta t` term (visited once per step), so the emitted angle is
        :math:`-\epsilon_p \Delta t = -2 \epsilon_p \Delta t/2`, accumulating :math:`RZ(-\epsilon_p t)`
        over the :math:`n` steps. The constant :math:`\epsilon_p/2` is deferred to the global phase (step 5).

        **4. Two-body diagonal**
        A two-body generator is :math:`D_l = \sum_{p,q}\lambda_{pq}\, n_p n_q`, with
        :math:`\lambda_{pq} =` ``core_tensors[l][p, q]``. Using :math:`n=(I-Z)/2`,

        .. math::

            \lambda_{pq}\, n_p n_q =
                \frac{\lambda_{pq}}{4}\left(I - Z_p - Z_q + Z_p Z_q\right) ,

        a constant :math:`\lambda_{pq}/4`, single-site terms
        :math:`-\tfrac{\lambda_{pq}}{4}(Z_p + Z_q)`, and the two-site term
        :math:`\tfrac{\lambda_{pq}}{4} Z_p Z_q`. In the *regrouped* input the single-site terms are
        already absorbed into ``core_tensors[0]`` and the constants into the global phase, so each
        two-body layer implements only the two-site term

        .. math::

            e^{-i(\lambda_{pq}/4) Z_p Z_q\, \tau} = \text{IsingZZ} \left(\lambda_{pq} \tfrac{\tau}{2}\right).

        Each two-body fragment is visited twice per step at :math:`\tau = \Delta t/2`, so the emitted
        angle is :math:`\tfrac{1}{2}\,\lambda_{pq}\,(\Delta t/2)` (the ``0.5`` prefactor in the code),
        accumulating :math:`IsingZZ(\lambda_{pq}\, t/2)` over the :math:`n` steps.

        **5. Constant terms (global phase / energy shift)**
        All identity contributions are collected into a single
        scalar :math:`s` and applied as one :class:`~.GlobalPhase` with angle :math:`s\,t`, i.e.
        :math:`e^{-ist}`, matching the :math:`I`-part of :math:`e^{-iHt}`. Following Eq. (A29) of
        `arXiv:2506.15784 <https://arxiv.org/abs/2506.15784>`__,

        .. math::

            s = C + \sum_p \epsilon_p
                  - \frac{1}{2}\sum_{l\ge 1}\sum_{p,q} \lambda^{(l)}_{pq}
                  + \frac{1}{4}\sum_{l\ge 1}\sum_{p} \lambda^{(l)}_{pp}.

        Here, we got the energy shift (``trace(core_tensors[0])`` for the
        one-body part and ``-sum(core_tensors[1:])/2 + trace(core_tensors[1:])/4`` for the two-body
        part).

    """

    dynamic_argnames = ("evolution_time",)
    hybrid_argnames = ("hamiltonian",)
    # `hybrid_argnames` and `compilable_argnames` cannot both be non-empty on the same
    # operator, so `num_trotter_steps` (a plain Python int that drives Python-level
    # control flow) is treated as `static_argnames` instead.
    static_argnames = ("num_trotter_steps", "double_phase")

    def __init__(self, evolution_time, num_trotter_steps, hamiltonian, wires, double_phase=False):
        Z = hamiltonian["core_tensors"]
        U = hamiltonian["leaf_tensors"]
        if not (Z.ndim == 3 and U.ndim == 3):
            raise ValueError(
                "TrotterCDF expects a CDF Hamiltonian with core_tensors.ndim == 3 and "
                f"leaf_tensors.ndim == 3. Got core_tensors.ndim={Z.ndim}, "
                f"leaf_tensors.ndim={U.ndim}. For vibrational (CGF) Hamiltonians, use TrotterCGF."
            )
        super().__init__(evolution_time, num_trotter_steps, hamiltonian, wires, double_phase)


def _apply_system_basis_rotation(U, wires):
    """Apply a fragment's basis rotation on the alpha and beta spin channels."""
    if math.is_abstract(U) or not np.allclose(U, np.eye(len(U))):
        BasisRotation(unitary_matrix=U, wires=wires[::2])
        BasisRotation(unitary_matrix=U, wires=wires[1::2])


def _merge_leaves(U_prev, U_curr):
    """Fragment-rotation merge rule ``U_prev^T @ U_curr`` (single ``(N, N)`` matmul)."""
    return U_prev.T @ U_curr


def _transpose_leaf(U):
    """Transpose (adjoint for real orthogonal rotations) of a leaf."""
    return U.T


def _apply_two_body_diagonal(Z, wires, first_order_time_step, control_wires, double_phase):
    """Apply the two-body ``IsingZZ`` layer (base / double-phase / genuine controlled)."""
    num_cas = Z.shape[0]
    # The shared CNOT sandwich is only used by the double-phase construction; the genuine
    # controlled circuit controls each IsingZZ individually inside ``_emit_two_body_isingzz``.
    sandwich = len(control_wires) > 0 and double_phase

    def zz_rotations(wire_idx0):

        @for_loop(wire_idx0 + 1, 2 * num_cas)
        def _zz_rotations(wire_idx1):
            # Two-body prefactor derivation. A fragment's two-body term is a sum of
            # number-operator products lambda_{kl} n_p n_q with n_p = (I - Z_p)/2, whose
            # Z_p Z_q piece is (lambda/4) Z_p Z_q. The target exp(-i (lambda/4) Z_p Z_q t)
            # equals IsingZZ(lambda t / 2) since IsingZZ(theta) = exp(-i theta Z Z / 2).
            # Each two-body fragment is visited TWICE per Trotter step (forward + backward)
            # at duration first_order_time_step = dt_trotter / 2, so to accumulate the total
            # IsingZZ angle lambda * dt_trotter we need angle-per-visit
            #   = lambda * dt_trotter / 2 = lambda * first_order_time_step.
            # With the extra 1/2 from IsingZZ (lambda t / 2) this gives beta_twoB = +0.5.
            angle = 0.5 * Z[wire_idx0 // 2, wire_idx1 // 2] * first_order_time_step
            _emit_two_body_isingzz(
                angle, wires[wire_idx0], wires[wire_idx1], control_wires, double_phase
            )

        if sandwich:
            CNOT([control_wires[0], wires[wire_idx0]])
        _zz_rotations()
        if sandwich:
            CNOT([control_wires[0], wires[wire_idx0]])

    for wire_idx0 in range(2 * num_cas - 1):
        zz_rotations(wire_idx0)


def _apply_one_body_diagonal(Z_one_body, wires, first_order_time_step, control_wires, double_phase):
    """Apply the one-body ``RZ`` layer (base / double-phase / genuine controlled)."""
    num_cas = Z_one_body.shape[0]

    @for_loop(2 * num_cas)
    def z_rotations(wire_idx):
        # One-body prefactor derivation (identical to CGF).
        #   n_p = (I - Z_p) / 2  ->  the Z-piece of eps n_p has coefficient -eps/2.
        #   target operator exp(-i eps n_p t) has Z-piece exp(+i eps t / 2 Z) = RZ(-eps t).
        #   The one-body fragment is visited ONCE per Trotter step, at duration
        #   first_order_time_step = dt_trotter / 2, so to accumulate a total RZ angle of
        #   -eps * dt_trotter we need angle-per-step = -2 * eps * first_order_time_step,
        #   i.e. alpha_oneB = -2.
        angle = -2.0 * Z_one_body[wire_idx // 2, wire_idx // 2] * first_order_time_step
        _emit_one_body_rz(angle, wires[wire_idx], control_wires, double_phase)

    z_rotations()


def _energy_shift(hamiltonian):
    """Zero-of-energy shift applied as a ``GlobalPhase`` (or control ``RZ``)."""
    nuc_constant = hamiltonian.get("nuc_constant", 0.0)
    Z_tensor = hamiltonian["core_tensors"]
    # Eq. (A29) first line: nuc + sum_k Z^(0)_{k,k}
    #   - (sum_{l,k,l'} Z^(l)_{k,l'}) / 2 + (sum_{l,k} Z^(l)_{k,k}) / 4
    phase_from_mod_one_body = math.trace(Z_tensor[0])
    phase_from_two_body = (
        -math.sum(Z_tensor[1:]) / 2 + math.sum(math.trace(Z_tensor[1:], axis1=1, axis2=2)) / 4
    )
    return nuc_constant + phase_from_mod_one_body + phase_from_two_body


_CDF_HELPERS = {
    "apply_system_basis_rotation": _apply_system_basis_rotation,
    "apply_two_body_diagonal": _apply_two_body_diagonal,
    "apply_one_body_diagonal": _apply_one_body_diagonal,
    "merge_leaves": _merge_leaves,
    "transpose_leaf": _transpose_leaf,
}


def _cdf_resource_counts(num_trotter_steps, hamiltonian, has_control, double_phase=False):
    """Shared (upper-bound) gate counts for the base and controlled CDF circuits.

    The exact gate count can be lower at runtime because fragments whose basis rotation
    happens to be the identity are skipped when the Hamiltonian data is concrete (not
    traced); this estimate assumes no such fragment is skipped.
    """
    if num_trotter_steps <= 0:
        return {}

    leaf_tensors = hamiltonian["leaf_tensors"]
    num_two_body_fragments = leaf_tensors.shape[0] - 1
    num_cas = leaf_tensors.shape[-1]

    resources = defaultdict(int)
    num_sysrot_calls = num_trotter_steps * (2 * num_two_body_fragments + 1) + 1
    num_twobody_blocks = num_trotter_steps * 2 * num_two_body_fragments
    num_onebody_blocks = num_trotter_steps
    num_twobody_rotations = num_twobody_blocks * num_cas * (2 * num_cas - 1)
    num_onebody_rotations = num_onebody_blocks * 2 * num_cas

    sysrot_key = BasisRotation(Complex[num_cas, num_cas], wires=Wire[num_cas])
    resources[sysrot_key] += 2 * num_sysrot_calls

    if not has_control:
        resources[IsingZZ] += num_twobody_rotations
        resources[RZ] += num_onebody_rotations
        resources[GlobalPhase] += 1
    elif double_phase:
        # Double-phase (Fig. 6): bare IsingZZ / RZ rotations, plus one CNOT pair around
        # each diagonal block, plus an RZ on the control wire for the global phase.
        resources[IsingZZ] += num_twobody_rotations
        resources[RZ] += num_onebody_rotations
        resources[CNOT] += num_twobody_blocks * 2 * (2 * num_cas - 1)
        resources[CNOT] += num_onebody_blocks * 4 * num_cas
        resources[RZ] += 1
    else:
        # Genuine controlled: each IsingZZ -> controlled-IsingZZ (4 CNOT + 2 RZ) and each
        # RZ -> controlled-RZ (2 CNOT + 2 RZ); the global phase becomes a PhaseShift on
        # the control wire. There are no bare IsingZZ gates.
        resources[RZ] += 2 * num_twobody_rotations + 2 * num_onebody_rotations
        resources[CNOT] += 4 * num_twobody_rotations + 2 * num_onebody_rotations
        resources[PhaseShift] += 1

    return dict(resources)


def _trotter_cdf_resources(evolution_time, num_trotter_steps, hamiltonian, wires, double_phase):
    return _cdf_resource_counts(num_trotter_steps, hamiltonian, has_control=False)


@register_resources(_trotter_cdf_resources, exact=False)
def _trotter_cdf_decomposition(evolution_time, num_trotter_steps, hamiltonian, wires, double_phase):
    # ``double_phase`` only affects the controlled decomposition; the base operator is
    # always the plain (uncontrolled) e^{-iHt} circuit.
    if num_trotter_steps > 0:
        _run_trotter_steps(
            evolution_time, num_trotter_steps, hamiltonian, wires, (), **_CDF_HELPERS
        )
        phi = (_energy_shift(hamiltonian) * evolution_time) % (4 * np.pi)
        GlobalPhase(phi)


add_decomps(TrotterCDF, _trotter_cdf_decomposition)


def _controlled_trotter_cdf_resource(
    base, control_wires, control_values, work_wires, work_wire_type
):
    return _cdf_resource_counts(
        base.arguments["num_trotter_steps"],
        base.arguments["hamiltonian"],
        has_control=True,
        double_phase=base.arguments["double_phase"],
    )


@register_condition(lambda control_wires, **__: len(control_wires) == 1)
@register_resources(_controlled_trotter_cdf_resource, exact=False)
def _controlled_trotter_cdf_decomp(base, control_wires, control_values, work_wires, work_wire_type):
    evolution_time = base.arguments["evolution_time"]
    num_trotter_steps = base.arguments["num_trotter_steps"]
    hamiltonian = base.arguments["hamiltonian"]
    wires = base.arguments["wires"]
    double_phase = base.arguments["double_phase"]

    if num_trotter_steps == 0:
        return

    phi = (_energy_shift(hamiltonian) * evolution_time) % (4 * np.pi)

    if double_phase:
        # Double-phase (Fig. 6) circuit: each full-time diagonal block is CNOT-sandwiched by
        # the control wire, so the bare rotations give control-0 / control-1 branches
        # e^{-i(H - s)t} / e^{+i(H - s)t}, where s = _energy_shift is the identity part of H.
        # We apply the energy shift explicitly and symmetrically as RZ(2*phi) on the control
        # wire (= diag(e^{-i s t}, e^{+i s t})), making the branches exactly the full-time
        # e^{-iHt} / e^{+iHt}.
        _run_trotter_steps(
            evolution_time,
            num_trotter_steps,
            hamiltonian,
            wires,
            control_wires,
            True,
            **_CDF_HELPERS,
        )
        RZ(2 * phi, control_wires)
        return

    # Genuine controlled unitary: control each diagonal rotation at the full angle (basis
    # rotations stay uncontrolled and telescope to the identity in the control-0 branch),
    # and apply the global phase as controlled-GlobalPhase(phi) = PhaseShift(-phi).
    _run_trotter_steps(
        evolution_time,
        num_trotter_steps,
        hamiltonian,
        wires,
        control_wires,
        False,
        **_CDF_HELPERS,
    )
    PhaseShift(-phi, control_wires)


add_decomps("C(TrotterCDF)", flip_zero_control2(_controlled_trotter_cdf_decomp))
