int i = 4;
const int j = i;
const int neg = -j;
bit[3] c = "000";
let alias = c;
const bit k = j + alias;
const float[3] arr = {0.0, 1.0, 2.0};
let arr_alias = arr[0:2];
let literal_alias = arr[0];
complex[float[64]] comp;
comp = 2.5 + 3.5im;
