name: Bug report
description: File a bug report
title: '[BUG]'
labels: "bug :bug:"

body:
  - type: markdown
    id: description
    attributes:
      value: |
          ## Before posting a bug report
          Search existing GitHub issues to make sure the issue does not already exist:
          https://github.com/xanaduai/pennylane/issues

          For general technical details check out our documentation:
          https://pennylane.readthedocs.io

          # Issue description
          Description of the issue - include code snippets in the Source code section below and screenshots if relevant.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        What do you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: |
        What actually happens?
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: |
        Please provide any additional information here that might be necessary to reproduce the issue. This includes details about reproducibility (What percentage of the time does it reproduce?).
  - type: textarea
    id: sourcecode
    attributes:
      label: Source code
      description: Please include a minimal non-working example, or any other code related to the issue, here. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: tracebacks
    attributes:
      label:  Tracebacks
      description: Please include the error tracebacks related to the issue here. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: system
    attributes:
      label:  System information
      description: Please post the output of `import pennylane as qml; qml.about()` or, if not possible/relevant, a note on why this is not included. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      options:
        - label: I have searched existing GitHub issues to make sure the issue does not already exist.
          required: true
