# Copyright 2026 Xanadu Quantum Technologies Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Code for resource estimation"""

import copy
import json
import os
import tempfile
import time
from collections import defaultdict
from functools import partial
from typing import TYPE_CHECKING

import pennylane as qp

from .specs import specs
from .utils import get_last_tape_transform_level, get_marker_level_map, preprocess_level_input

_RESOURCE_ESTIMATION_PREFIX = "pennylane_resource_estimation"

if TYPE_CHECKING:
    from pennylane.transforms.core import CompilePipeline


def _get_decomposition_rules(
    qnode, compile_pipeline: "CompilePipeline", level: list[int] | int, *args, **kwargs
) -> list[dict[str, dict[str, int]]]:
    """
    Get all of the decomposition rules by querying the graph solver.

    Args:
        qnode: The (qjit'd) QNode to estimate resources for.
        compile_pipeline (CompilePipeline): The compile pipeline to use for decomposition.
        level (list[int] | int): The level(s) to estimate resources for.
        *args: Additional positional arguments to pass to the QNode.
        **kwargs: Additional keyword arguments to pass to the QNode.

    Returns:
        list[dict[str, dict[str, int]]]: A list containing the decomposition rules
    """
    from catalyst import QJIT

    all_decomps = []
    resource_fnames = []

    max_level = max(level) if isinstance(level, (list, tuple)) else level

    # This new compile pipeline will ONLY contain decomposition passes (used to generate the
    #   decomposition rules for each level)
    new_compile_pipeline = qp.CompilePipeline()

    with tempfile.TemporaryDirectory(
        prefix=f"{_RESOURCE_ESTIMATION_PREFIX}_{os.getpid()}_"
    ) as tmpdirname:
        fname_prefix = f"{tmpdirname}/{_RESOURCE_ESTIMATION_PREFIX}_{time.time_ns()}_level_"

        for i, mlir_pass in enumerate(compile_pipeline):
            if i > max_level:
                break
            if mlir_pass.pass_name == "graph-decomposition":
                estimation_fpath = f"{fname_prefix}{i}.json"
                resource_fnames.append(estimation_fpath)
                new_pass = copy.deepcopy(mlir_pass)
                new_pass.kwargs["est_json_path"] = estimation_fpath
                new_compile_pipeline += new_pass

        new_qnode = copy.copy(qnode.original_function)
        # Need to manually set the compile pipeline internal variable for the new qnode
        new_qnode._compile_pipeline = new_compile_pipeline
        compile_options = copy.deepcopy(qnode.compile_options)

        new_qnode = QJIT(new_qnode, compile_options)
        new_qnode.jit_compile(args, **kwargs)

        # Load in the decomposition rules from the JSON files generated by the graph decomposition pass
        for resource_fname in resource_fnames:
            with open(resource_fname, "r") as f:
                decomps = json.load(f)
                all_decomps.append(decomps)

    return all_decomps


def _estimate_impl(qnode, level, *args, **kwargs):
    compile_pipeline = qnode.original_function.compile_pipeline

    if get_last_tape_transform_level(compile_pipeline) != 0:
        raise ValueError("Resource estimation is not supported with tape transforms.")

    return_single_level: bool = isinstance(level, (int, str)) and level not in (
        "all",
        "all-mlir",
    )

    # Easier to assume level is always a sorted list of int levels
    level = preprocess_level_input(
        level, get_marker_level_map(compile_pipeline), len(compile_pipeline), 0
    )
    # TODO: Level is now processed, but is still unused

    top_level_specs = specs(qnode, level=0)(*args, **kwargs)
    all_decomps = _get_decomposition_rules(qnode, compile_pipeline, level, *args, **kwargs)

    resources = top_level_specs.resources.gate_types
    for decomps in all_decomps:
        new_resources = {}
        for gate, count in resources.items():
            if gate not in decomps:
                raise RuntimeError(f"Gate {gate} not found in decomposition rules")
            for decomp_gate, decomp_count in decomps[gate].items():
                if decomp_gate not in new_resources:
                    new_resources[decomp_gate] = 0
                new_resources[decomp_gate] += count * decomp_count
        resources = new_resources

    return resources


def estimate(qnode, level="user"):
    return partial(_estimate_impl, qnode, level)
