# Copyright 2026 Xanadu Quantum Technologies Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Code for resource estimation"""

import copy
import json
import os
import tempfile
import time
from collections import defaultdict
from functools import partial
from typing import TYPE_CHECKING

import pennylane as qp

from ._utils import get_last_tape_transform_level, get_marker_level_map, preprocess_level_input
from .specs import specs

_RESOURCE_ESTIMATION_PREFIX = "pennylane_resource_estimation"

if TYPE_CHECKING:
    from pennylane.transforms.core import CompilePipeline


def _convert_levels_to_decompose_order(
    level: list[int], compile_pipeline: "CompilePipeline"
) -> list[int]:
    """Convert a list of levels into the an indexed list of which decomposition comes immediately before them.

    This effectively converts each level number into a list of how many decompositions come before it.

    For example, in the following compile pipeline:
    [1] l1
    [2] decompose
    [3] l2
    [4] l3
    [5] decompose
    The list `[1,2,3,4,5]` would be converted to `[0,1,1,1,2]`.

    .. note::

        This function assumes that `level` is a sorted list of integers, and that no tape transforms are present in the list.

    .. warning::

        This function is intended for internal use only and may change or be removed in future releases.

    Args:
        level (list[int]): The levels to convert.
        compile_pipeline (CompilePipeline): The compile pipeline to use for decomposition.

    Returns:
        list[int]: The number of decompositions that come immediately before each level.
    """
    decompose_count = 0
    decompose_levels = []
    if 0 in level:
        decompose_levels.append(0)
    for i, mlir_pass in enumerate(compile_pipeline):
        if mlir_pass.pass_name == "graph-decomposition":
            decompose_count += 1
        if i + 1 in level:
            decompose_levels.append(decompose_count)
    return decompose_levels


def _get_decomposition_rules(
    qnode, compile_pipeline: "CompilePipeline", level: list[int] | int, *args, **kwargs
) -> list[dict[str, dict[str, int]]]:
    """
    Get all of the decomposition rules by querying the graph solver.

    Args:
        qnode: The (qjit'd) QNode to estimate resources for.
        compile_pipeline (CompilePipeline): The compile pipeline to use for decomposition.
        level (list[int] | int): The level(s) to estimate resources for.
        *args: Additional positional arguments to pass to the QNode.
        **kwargs: Additional keyword arguments to pass to the QNode.

    Returns:
        list[dict[str, dict[str, int]]]: A list containing the decomposition rules
    """
    from catalyst import QJIT

    all_decomps = []
    resource_fnames = []

    max_level = max(level) if isinstance(level, (list, tuple)) else level

    # This new compile pipeline will ONLY contain decomposition passes (used to generate the
    #   decomposition rules for each level)
    new_compile_pipeline = qp.CompilePipeline()

    with tempfile.TemporaryDirectory(
        prefix=f"{_RESOURCE_ESTIMATION_PREFIX}_{os.getpid()}_"
    ) as tmpdirname:
        fname_prefix = f"{tmpdirname}/{_RESOURCE_ESTIMATION_PREFIX}_{time.time_ns()}_level_"

        for i, mlir_pass in enumerate(compile_pipeline):
            if i > max_level:
                break
            if mlir_pass.pass_name == "graph-decomposition":
                estimation_fpath = f"{fname_prefix}{i}.json"
                resource_fnames.append(estimation_fpath)
                new_pass = copy.deepcopy(mlir_pass)
                new_pass.kwargs["est_json_path"] = estimation_fpath
                new_compile_pipeline += new_pass

        new_qnode = copy.copy(qnode.original_function)
        # Need to manually set the compile pipeline internal variable for the new qnode
        new_qnode._compile_pipeline = new_compile_pipeline
        compile_options = copy.deepcopy(qnode.compile_options)

        new_qnode = QJIT(new_qnode, compile_options)
        new_qnode.jit_compile(args, **kwargs)

        # Load in the decomposition rules from the JSON files generated by the graph decomposition pass
        for resource_fname in resource_fnames:
            with open(resource_fname, "r") as f:
                decomps = json.load(f)
                all_decomps.append(decomps)

    return all_decomps


def _estimate_impl(qnode, level, *args, **kwargs):
    compile_pipeline = qnode.original_function.compile_pipeline

    if get_last_tape_transform_level(compile_pipeline) != 0:
        raise ValueError("Resource estimation is not supported with tape transforms.")

    return_single_level: bool = isinstance(level, (int, str)) and level not in (
        "all",
        "all-mlir",
    )

    # Easier to assume level is always a sorted list of int levels
    level = preprocess_level_input(
        level, get_marker_level_map(compile_pipeline), len(compile_pipeline), 0
    )

    initial_specs = specs(qnode, level=0)(*args, **kwargs)
    all_decomps = _get_decomposition_rules(qnode, compile_pipeline, level, *args, **kwargs)

    # Convert level into the index notation used by the output from _get_decomposition_rules
    level = _convert_levels_to_decompose_order(level, compile_pipeline)

    current_resources = initial_specs.resources.gate_types
    all_resources = []

    if 0 in level:
        all_resources.append(current_resources)

    for i, decomps in enumerate(all_decomps, start=1):
        new_resources = {}
        for gate, count in current_resources.items():
            if gate not in decomps:
                raise RuntimeError(f"Gate {gate} not found in decomposition rules")
            for decomp_gate, decomp_count in decomps[gate].items():
                if decomp_gate not in new_resources:
                    new_resources[decomp_gate] = 0
                new_resources[decomp_gate] += count * decomp_count
        current_resources = new_resources
        if i in level:
            all_resources.append(current_resources)

    if return_single_level:
        return all_resources[0]

    return all_resources


def estimate(qnode, level="user"):
    return partial(_estimate_impl, qnode, level)
