# Copyright 2026 Xanadu Quantum Technologies Inc.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Code for resource estimation"""

import copy
from collections import defaultdict
import json
import tempfile
import os
import time
from functools import partial

import pennylane as qp

from .specs import specs
from .utils import get_last_tape_transform_level, preprocess_level_input, get_marker_level_map

_RESOURCE_ESTIMATION_PREFIX = "pennylane_resource_estimation"

def _estimate_impl(qnode, level, *args, **kwargs):
    from catalyst import QJIT

    original_qnode = qnode.original_function
    original_compile_pipeline = original_qnode.compile_pipeline
    new_compile_pipeline = qp.CompilePipeline()


    resource_fnames = []

    with tempfile.TemporaryDirectory(
        prefix=f"{_RESOURCE_ESTIMATION_PREFIX}_{os.getpid()}_"
    ) as tmpdirname:
        fname_prefix = f"{tmpdirname}/{_RESOURCE_ESTIMATION_PREFIX}_{time.time_ns()}_level_"

        for i, mlir_pass in enumerate(original_compile_pipeline):
            if mlir_pass.pass_name is None:
                continue  # Tape transform
            if mlir_pass.pass_name == "graph-decomposition":
                estimation_fpath = f"{fname_prefix}{i}.json"
                resource_fnames.append(estimation_fpath)
                new_pass = copy.deepcopy(mlir_pass)
                new_pass.kwargs["est_json_path"] = estimation_fpath
                new_compile_pipeline += new_pass

        new_qnode = copy.copy(original_qnode)
        # Need to manually set the compile pipeline internal variable for the new qnode
        new_qnode._compile_pipeline = new_compile_pipeline
        compile_options = copy.deepcopy(qnode.compile_options)

        new_qnode = QJIT(new_qnode, compile_options)
        new_qnode.jit_compile(args, **kwargs)
        top_level_specs = specs(new_qnode, level=0)(*args, **kwargs)

        all_decomps = []
        # Load in the decomposition rules from the JSON files generated by the graph decomposition pass
        for resource_fname in resource_fnames:
            with open(resource_fname, "r") as f:
                decomps = json.load(f)
                all_decomps.append(decomps)

    resources = top_level_specs.resources.gate_types
    for decomps in all_decomps:
        new_resources = {}
        for gate, count in resources.items():
            if gate not in decomps:
                raise RuntimeError(f"Gate {gate} not found in decomposition rules")
            for decomp_gate, decomp_count in decomps[gate].items():
                if decomp_gate not in new_resources:
                    new_resources[decomp_gate] = 0
                new_resources[decomp_gate] += count * decomp_count
        resources = new_resources

    return resources


def estimate(qnode, level="user"):
    return partial(_estimate_impl, qnode, level)
