name: Code Security Scan
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bandit:
    runs-on: ubuntu-latest
    
    permissions:
      security-events: write
    
    steps:
      - name: Perform PyCQA/bandit scan
        uses: PyCQA/bandit-action@v1
