name: External Fork check
on:
  pull_request: {}
  
jobs:
  check-external:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR and label
        shell: bash
        run: if github.event.pull_request.head.repo.fork==false; then 
            gh pr edit $GITHUB_EVENT_PATH --add-label "External"; fi