name: External Contributor Check
on:
  pull_request_target:
    types: 
      - opened   
  
jobs:
  check-external:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR and label
        with:
          org: "${{ github.repository_owner }}"
          team: "external-collaborators"
          github_token: ${{secrets.PENNYLANE_EXTERNAL_LABEL_MEMBER_CHECK}}
          username: "${{ github.actor }}"
        uses: XanaduAI/cloud-actions/label-external-pull-request@sc-86563-external-label-forks
        