name: External Fork check
on:
  pull_request: {}
  
jobs:
  check-external:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check PR and label
        run: if ${{ github.event.pull_request.head.repo.fork}}=='false'; then gh pr edit $GITHUB_HEAD_REF --add-label "External"; fi 