name: Enforce PennyLane alias as qp
permissions:
  contents: read

on:
  merge_group:
    types:
      - checks_requested
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_call:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine_runner:
    if: github.event.pull_request.draft == false
    name: Determine runner type to use
    uses: ./.github/workflows/determine-workflow-runner.yml
    with:
      default_runner: ubuntu-latest
      force_large_runner: ${{ github.event_name == 'merge_group' }}

  enforce-alias:
    if: github.event.pull_request.draft == false
    needs: [determine_runner]
    runs-on: ${{ needs.determine_runner.outputs.runner_group }}
    env:
      CORE_MODULES: >-
        pennylane/operation.py
        pennylane/qchem
        pennylane/ops
        pennylane/_grad
        pennylane/bose
        pennylane/capture
        pennylane/compiler
        pennylane/concurrency
        pennylane/control_flow
        pennylane/debugging
        pennylane/decomposition

      TEST_MODULES: >-
        tests/test_operation.py
        tests/qchem
        tests/ops

    name: Enforce PennyLane alias as qp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: 0.9.17
          enable-cache: true  

      - name: Enforce 'qp' Alias (Code)
        if: always()
        run: |
          uvx ruff check ${{ env.CORE_MODULES }} --select ICN --config "lint.flake8-import-conventions.aliases = { pennylane = 'qp' }" --config "lint.flake8-import-conventions.banned-aliases = { pennylane = ['qml'] }"

      - name: Enforce 'qp' Alias (Tests)
        if: always()
        run: |
          uvx ruff check ${{ env.TEST_MODULES }} --select ICN --config "lint.flake8-import-conventions.aliases = { pennylane = 'qp' }" --config "lint.flake8-import-conventions.banned-aliases = { pennylane = ['qml'] }"

      - name: Enforce 'qp' Alias (Documentation)
        if: always()
        run: |
          ! grep -rni "qml" ${{ env.CORE_MODULES }} ${{ env.TEST_MODULES }}
