name: Install Dependencies
on:
  workflow_call:
    inputs:
      python_version:
        description: The version of Python to use in order to run unit tests
        required: false
        type: string
        default: '3.9'
      install_jax:
        description: Indicate if JAX should be installed or not
        required: false
        type: boolean
        default: true
      jax_version:
        description: The version of JAX to install for any job that requires JAX
        required: false
        type: string
        default: 0.4.23
      install_tensorflow:
        description: Indicate if TensorFlow should be installed or not
        required: false
        type: boolean
        default: true
      tensorflow_version:
        description: The version of TensorFlow to install for any job that requires TensorFlow
        required: false
        type: string
        default: 2.15.0
      install_pytorch:
        description: Indicate if PyTorch should be installed or not
        required: false
        type: boolean
        default: true
      pytorch_version:
        description: The version of PyTorch to install for any job that requires PyTorch
        required: false
        type: string
        default: 2.2.0
      install_pennylane_lightning_master:
        description: Indicate if PennyLane-Lightning should be installed from the master branch
        required: false
        type: boolean
        default: true
      additional_pip_packages:
        description: Additional packages to install. Values will be passed to pip install {value}
        required: false
        type: string
        default: ''

jobs:
  dependencies:
    name: Install PennyLane and dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python_version }}'

      - name: Upgrade PIP
        run: pip install --upgrade pip && pip install wheel --upgrade

      - name: Install PennyLane dependencies
        run: |
          pip install -r requirements-ci.txt --upgrade
          pip install -r requirements-dev.txt --upgrade

      - name: Install PyTorch
        if: inputs.install_pytorch == true
        env:
          TORCH_VERSION: ${{ inputs.pytorch_version != '' && format('=={0}', inputs.pytorch_version) || '' }}
        run: pip install "torch${{ env.TORCH_VERSION }}" -f https://download.pytorch.org/whl/torch_stable.html

      - name: Install TensorFlow
        if: inputs.install_tensorflow == true
        env:
          TF_VERSION: ${{ inputs.tensorflow_version != '' && format('~={0}', inputs.tensorflow_version) || '' }}
        run: pip install "tensorflow${{ env.TF_VERSION }}" "keras${{ env.TF_VERSION }}"

      - name: Install JAX
        if: inputs.install_jax == true
        env:
          JAX_VERSION: ${{ inputs.jax_version != '' && format('=={0}', inputs.jax_version) || '' }}
        run: pip install "jax${{ env.JAX_VERSION}}" "jaxlib${{ env.JAX_VERSION }}"

      - name: Install additional PIP packages
        if: inputs.additional_pip_packages != ''
        run: pip install ${{ inputs.additional_pip_packages }}

      - name: Install PennyLane
        run: |
          python setup.py bdist_wheel
          pip install dist/PennyLane*.whl

      - name: Install PennyLane-Lightning master
        if: inputs.install_pennylane_lightning_master == true
        run: pip install -i https://test.pypi.org/simple/ PennyLane-Lightning --pre --upgrade
