name: "Pull Request Docs Check"
on: 
- pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "doc/"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        pre-build-command: "pip install requirements.txt && pip install . && pip install -r qchem/requirements.txt && pip install qchem"
