name: NumPy 1 - Tests
on:

  # This will be removed (I need to test it)  
  pull_request: 
    types:
        - opened
        - reopened
        - synchronize
        - ready_for_review

  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC (1 AM Toronto in winter, 2 AM in summer)

concurrency:
  group: numpy-1-unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/numpy_1_unit-tests.yml
    with:
      branch: ${{ github.ref }}
