name: NumPy 1 - Tests
on:

  schedule:
    # Runs daily at 6 AM UTC (1 AM Toronto in winter, 2 AM in summer)
    - cron: '0 6 * * *'  

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: numpy-1-unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/numpy_1_unit-tests.yml
    with:
      branch: ${{ github.ref }}
