name: NumPy 1 - Tests
on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC (1 AM Toronto in winter, 2 AM in summer)

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

env:
  DEPS_BRANCH: bot/stable-deps-update

jobs:
  tests:
    uses: ./.github/workflows/numpy_1_unit-tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      branch: ${{ github.ref }}

      # Run a 'lightened' version of the CI on Pull Requests by default
      # Unless the label `ci:run-full-test-suite` is attached to the PR.
      # Always runs the full suite for push events.
      run_lightened_ci: >-
        ${{
          github.event_name == 'pull_request'
          && !contains(github.event.pull_request.labels.*.name, 'ci:run-full-test-suite')
          || false
         }}
      pytest_store_durations: false
