name: NumPy 1 - Tests
on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC (1 AM Toronto in winter, 2 AM in summer)

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: ./.github/workflows/numpy_1_unit-tests.yml
    secrets:
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
    with:
      branch: ${{ github.ref }}
      
